import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import zlib from 'node:zlib';
import { decodePng, UnsupportedPngError, CorruptedPngError } from '../../studio/server/post-processing/png-decoder.js';
import { encodePng, createPngChunk, crc32 } from '../../studio/server/providers/png-builder.js';

/**
 * Helper to build custom PNGs with arbitrary chunks for testing edge cases.
 */
function buildCustomPng({
  width = 2,
  height = 2,
  bitDepth = 8,
  colorType = 6,
  compressionMethod = 0,
  filterMethod = 0,
  interlaceMethod = 0,
  palette = null,
  trns = null,
  scanlines = null,
  customChunksBeforeIdat = [],
  customChunksAfterIdat = [],
  skipIhdr = false,
  skipIend = false,
  corruptCrc = false
}) {
  const signature = Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]);
  const chunks = [];

  if (!skipIhdr) {
    const ihdrData = Buffer.alloc(13);
    ihdrData.writeUInt32BE(width, 0);
    ihdrData.writeUInt32BE(height, 4);
    ihdrData.writeUInt8(bitDepth, 8);
    ihdrData.writeUInt8(colorType, 9);
    ihdrData.writeUInt8(compressionMethod, 10);
    ihdrData.writeUInt8(filterMethod, 11);
    ihdrData.writeUInt8(interlaceMethod, 12);
    chunks.push(createPngChunk('IHDR', ihdrData));
  }

  if (palette) {
    const plteData = Buffer.from(palette);
    chunks.push(createPngChunk('PLTE', plteData));
  }

  if (trns) {
    const trnsData = Buffer.from(trns);
    chunks.push(createPngChunk('tRNS', trnsData));
  }

  for (const c of customChunksBeforeIdat) {
    chunks.push(createPngChunk(c.type, c.data));
  }

  if (scanlines) {
    const compressed = zlib.deflateSync(scanlines);
    if (corruptCrc) {
      // Craft a chunk with bad CRC
      const typeBuf = Buffer.from('IDAT', 'ascii');
      const lenBuf = Buffer.alloc(4);
      lenBuf.writeUInt32BE(compressed.length, 0);
      const badCrcBuf = Buffer.alloc(4);
      badCrcBuf.writeUInt32BE(12345678, 0);
      chunks.push(Buffer.concat([lenBuf, typeBuf, compressed, badCrcBuf]));
    } else {
      chunks.push(createPngChunk('IDAT', compressed));
    }
  }

  for (const c of customChunksAfterIdat) {
    chunks.push(createPngChunk(c.type, c.data));
  }

  if (!skipIend) {
    chunks.push(createPngChunk('IEND', Buffer.alloc(0)));
  }

  return Buffer.concat([signature, ...chunks]);
}

describe('PNG Decoder Unit Test Suite', () => {
  test('Round-trip decodes Type 6 (RGBA) generated by encodePng', () => {
    const width = 4;
    const height = 4;
    const rgba = Buffer.alloc(width * height * 4);
    for (let i = 0; i < rgba.length; i += 4) {
      rgba[i] = 10;     // R
      rgba[i + 1] = 20; // G
      rgba[i + 2] = 30; // B
      rgba[i + 3] = 255;// A
    }
    // Set one specific pixel to distinct color
    rgba[0] = 255; rgba[1] = 0; rgba[2] = 128; rgba[3] = 200;

    const encoded = encodePng(width, height, rgba);
    const decoded = decodePng(encoded);

    assert.equal(decoded.width, 4);
    assert.equal(decoded.height, 4);
    assert.deepEqual(decoded.getPixel(0, 0), { r: 255, g: 0, b: 128, a: 200 });
    assert.deepEqual(decoded.getPixel(1, 0), { r: 10, g: 20, b: 30, a: 255 });
  });

  test('Decodes Type 2 (RGB) with and without tRNS', () => {
    // 2x1 RGB image: pixel 0 is [255, 0, 0], pixel 1 is [0, 255, 0]
    // Filter byte 0 (None) + 6 bytes of RGB
    const scanlines = Buffer.from([0, 255, 0, 0, 0, 255, 0]);

    // Without tRNS: alpha should be 255
    const pngNoTrns = buildCustomPng({
      width: 2,
      height: 1,
      colorType: 2,
      scanlines
    });
    const decNoTrns = decodePng(pngNoTrns);
    assert.deepEqual(decNoTrns.getPixel(0, 0), { r: 255, g: 0, b: 0, a: 255 });
    assert.deepEqual(decNoTrns.getPixel(1, 0), { r: 0, g: 255, b: 0, a: 255 });

    // With tRNS matching pixel 0 [255, 0, 0]
    const trnsBuf = Buffer.alloc(6);
    trnsBuf.writeUInt16BE(255, 0); // R
    trnsBuf.writeUInt16BE(0, 2);   // G
    trnsBuf.writeUInt16BE(0, 4);   // B

    const pngWithTrns = buildCustomPng({
      width: 2,
      height: 1,
      colorType: 2,
      trns: trnsBuf,
      scanlines
    });
    const decWithTrns = decodePng(pngWithTrns);
    assert.deepEqual(decWithTrns.getPixel(0, 0), { r: 255, g: 0, b: 0, a: 0 }); // Keyed transparent
    assert.deepEqual(decWithTrns.getPixel(1, 0), { r: 0, g: 255, b: 0, a: 255 });
  });

  test('Decodes Type 3 (Indexed) with PLTE and tRNS', () => {
    // Palette: index 0 = [255, 0, 0], index 1 = [0, 0, 255]
    const palette = [255, 0, 0, 0, 0, 255];
    // tRNS: index 0 alpha = 128, index 1 alpha = 255
    const trns = [128, 255];
    // 2x1 image with index 0 and index 1
    const scanlines = Buffer.from([0, 0, 1]);

    const png = buildCustomPng({
      width: 2,
      height: 1,
      colorType: 3,
      palette,
      trns,
      scanlines
    });
    const dec = decodePng(png);
    assert.deepEqual(dec.getPixel(0, 0), { r: 255, g: 0, b: 0, a: 128 });
    assert.deepEqual(dec.getPixel(1, 0), { r: 0, g: 0, b: 255, a: 255 });
  });

  test('Decodes Type 0 (Grayscale) with and without tRNS', () => {
    // 2x1 Grayscale: pixel 0 is 50, pixel 1 is 100
    const scanlines = Buffer.from([0, 50, 100]);

    // tRNS for grayscale 50
    const trnsBuf = Buffer.alloc(2);
    trnsBuf.writeUInt16BE(50, 0);

    const png = buildCustomPng({
      width: 2,
      height: 1,
      colorType: 0,
      trns: trnsBuf,
      scanlines
    });
    const dec = decodePng(png);
    assert.deepEqual(dec.getPixel(0, 0), { r: 50, g: 50, b: 50, a: 0 });
    assert.deepEqual(dec.getPixel(1, 0), { r: 100, g: 100, b: 100, a: 255 });
  });

  test('Unfilters RFC 2083 across all 5 filter types (Sub, Up, Average, Paeth)', () => {
    // 2x2 image, Type 0 (1 bpp)
    // Row 0: Filter 1 (Sub). Raw bytes: [10, 20] -> unfiltered: [10, 30]
    // Row 1: Filter 4 (Paeth). Raw bytes: [5, 10]
    // For row 1, col 0: Raw=5, Left=0, Prior=10, PriorLeft=0 -> Paeth(0, 10, 0)=10 -> 5+10 = 15
    // For row 1, col 1: Raw=10, Left=15, Prior=30, PriorLeft=10 -> Paeth(15, 30, 10):
    //   p = 15 + 30 - 10 = 35. pa = |35-15|=20, pb = |35-30|=5, pc = |35-10|=25.
    //   min is pb -> Prior = 30. Out = 10 + 30 = 40.
    const scanlines = Buffer.from([
      1, 10, 20, // Filter 1 (Sub)
      4, 5, 10   // Filter 4 (Paeth)
    ]);

    const png = buildCustomPng({
      width: 2,
      height: 2,
      colorType: 0,
      scanlines
    });
    const dec = decodePng(png);
    assert.equal(dec.getPixel(0, 0).r, 10);
    assert.equal(dec.getPixel(1, 0).r, 30);
    assert.equal(dec.getPixel(0, 1).r, 15);
    assert.equal(dec.getPixel(1, 1).r, 40);
  });

  test('Fail-fast defense: file size > 20 MiB is rejected', () => {
    const hugeBuf = Buffer.alloc(20 * 1024 * 1024 + 1);
    assert.throws(() => decodePng(hugeBuf), UnsupportedPngError);
  });

  test('Fail-fast defense: invalid signature is rejected', () => {
    const badSig = Buffer.from([0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77]);
    assert.throws(() => decodePng(badSig), CorruptedPngError);
  });

  test('Fail-fast defense: bad CRC is rejected', () => {
    const pngBadCrc = buildCustomPng({
      width: 2,
      height: 1,
      colorType: 0,
      scanlines: Buffer.from([0, 10, 20]),
      corruptCrc: true
    });
    assert.throws(() => decodePng(pngBadCrc), CorruptedPngError);
  });

  test('Fail-fast defense: reserved bit on 3rd char of chunk type is rejected', () => {
    // Custom chunk 'IDaT' where 3rd char 'a' has bit 5 set (lowercase)
    const pngReserved = buildCustomPng({
      width: 2,
      height: 1,
      colorType: 0,
      scanlines: Buffer.from([0, 10, 20]),
      customChunksBeforeIdat: [{ type: 'tExt', data: Buffer.alloc(0) }]
    });
    assert.throws(() => decodePng(pngReserved), (err) => {
      return err instanceof CorruptedPngError && err.message.includes('reserved bit is set');
    });
  });

  test('Fail-fast defense: strict tRNS mode rejects 16-bit values > 0x00FF', () => {
    const scanlines = Buffer.from([0, 50, 100]);
    const trnsBuf = Buffer.alloc(2);
    trnsBuf.writeUInt16BE(0x0150, 0); // > 0x00FF

    const png = buildCustomPng({
      width: 2,
      height: 1,
      colorType: 0,
      trns: trnsBuf,
      scanlines
    });

    // Default mode succeeds with masking
    const decDefault = decodePng(png, { strictTrns: false });
    assert.ok(decDefault);

    // Strict mode throws CorruptedPngError
    assert.throws(() => decodePng(png, { strictTrns: true }), CorruptedPngError);
  });

  test('Fail-fast defense: duplicate PLTE, missing PLTE for indexed, and missing IEND rejected', () => {
    // Duplicate PLTE
    const duplicatePltePng = buildCustomPng({
      width: 1,
      height: 1,
      colorType: 3,
      palette: [255, 0, 0],
      customChunksBeforeIdat: [{ type: 'PLTE', data: Buffer.from([0, 255, 0]) }],
      scanlines: Buffer.from([0, 0])
    });
    assert.throws(() => decodePng(duplicatePltePng), CorruptedPngError);

    // Missing PLTE for Type 3
    const missingPltePng = buildCustomPng({
      width: 1,
      height: 1,
      colorType: 3,
      scanlines: Buffer.from([0, 0])
    });
    assert.throws(() => decodePng(missingPltePng), CorruptedPngError);

    // Missing IEND
    const missingIendPng = buildCustomPng({
      width: 1,
      height: 1,
      colorType: 0,
      scanlines: Buffer.from([0, 0]),
      skipIend: true
    });
    assert.throws(() => decodePng(missingIendPng), CorruptedPngError);
  });
});
